<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>top.mddata.base</groupId>
        <artifactId>md-sa-token</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>sa-token-oauth2-core</artifactId>
    <name>${project.artifactId}</name>
    <description>sa-token oauth2 标准协议出入参实体（RFC 6749 / RFC 7009 / OIDC）</description>

    <dependencies>
        <dependency>
            <groupId>top.mddata.base</groupId>
            <artifactId>md-annotation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>
</project>
